<footer class="footer">
	<div class="container">
		<p> Code licensed under the <a href="https://opensource.org/licenses/MIT"> MIT License </a> and the docs are licensed under <a href="https://creativecommons.org/licenses/by/3.0/"> CC BY 3.0</a>. </p>
		
		<p> Bugflux · <a class="inacessible"> Blog </a> · <a class="inacessible"> Forum </a> · <a href="https://github.com/bugflux-com"> GitHub </a></p>
	</div>
</footer>